In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# broadcast a numpy array

arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# broadcast a numpy array

slice_of_array = arr[0:6]

In [13]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_array[:] = 99

In [16]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
# if you don't want to edit original array...

arr_copy = arr.copy()

In [19]:
arr_copy[:] = 10000

In [20]:
arr_copy

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
# indexing on a two-dimenstional array

arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [23]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
arr_2d.shape

(3, 3)

In [25]:
# return row

arr_2d[1]

array([20, 25, 30])

In [26]:
arr_2d[1][1]

25

In [27]:
# alternate way to return same value

arr_2d[1, 1]

25

In [28]:
arr_2d[2, 2]

45

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
# return rows between 0 and 2 (not including 2)

arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [31]:
# return rows between 0 and 2 (not including 2); start at column 1 and select everything thereafter

arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [32]:
# conditional selection

arr = np.arange(1, 11)

In [33]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
bool_array = arr > 4

In [36]:
bool_array

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [37]:
# returns values where bool is True

arr[bool_array]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
# steps above combined into one line

arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [39]:
arr[arr == 2]

array([2])

In [40]:
arr[arr <= 6]

array([1, 2, 3, 4, 5, 6])