In [2]:
import numpy as np

In [3]:
mylist = [1, 2, 3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
arr = np.array(mylist)

In [7]:
arr

array([1, 2, 3])

In [8]:
mylist = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
mymatrix = np.array(mylist)

In [12]:
mymatrix.shape

(3, 3)

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones((5, 5,))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.ones((5, 5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [21]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [24]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [25]:
# identity matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(1)

array([0.18795369])

In [27]:
# uniform distribution; return random numbers between 0 and 1

np.random.rand(5, 5)

array([[0.82379782, 0.39060276, 0.83421503, 0.20566292, 0.80802616],
       [0.26501106, 0.268971  , 0.21102399, 0.50151341, 0.30833709],
       [0.14295439, 0.66393737, 0.45892037, 0.26011652, 0.60748839],
       [0.88489114, 0.34954024, 0.43603516, 0.74819077, 0.10913673],
       [0.89987907, 0.34304848, 0.25561409, 0.33236125, 0.64275565]])

In [28]:
# standard normal distribution; mean = 0, standard deviation = 1

np.random.randn(1)

array([-0.63365289])

In [3]:
# loc = mean, scale = standard deviation

np.random.normal(loc=1, scale=3)

1.3898463550813847

In [31]:
np.random.randint(0, 100)

22

In [35]:
# seed must be in same cell

np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [36]:
arr = np.arange(25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
random_arr = np.random.randint(0, 50, 10)

In [43]:
random_arr

array([ 8, 19, 10, 12, 31, 43, 23,  0, 41,  9])

In [44]:
arr.shape

(25,)

In [45]:
# change one dimensional array into something else

arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
random_arr

array([ 8, 19, 10, 12, 31, 43, 23,  0, 41,  9])

In [47]:
random_arr.max()

43

In [48]:
random_arr.min()

0

In [49]:
random_arr.argmax()

5

In [50]:
random_arr.argmin()

7

In [54]:
random_arr.dtype

dtype('int32')