In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [5]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [6]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
(arr + 2) / 100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# perform addition on a element by element basis

arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# numpy doesn't produce an error when dividing by zero; nan = not a number

1 / arr

C:\Users\steve\AppData\Local\Temp\ipykernel_15908\1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [11]:
arr / arr

C:\Users\steve\AppData\Local\Temp\ipykernel_15908\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [14]:
np.log(arr)

C:\Users\steve\AppData\Local\Temp\ipykernel_15908\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [15]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [16]:
arr.sum()

45

In [17]:
arr.mean()

4.5

In [18]:
arr.max()

9

In [19]:
arr.min()

0

In [25]:
# axis logic with two dimensional arrays

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [26]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr_2d.shape

(3, 4)

In [28]:
# this will sum all the numbers

arr_2d.sum()

78

In [29]:
# sum across the rows; sum of the columns

arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [30]:
# sum across the columns; sum of the rows

arr_2d.sum(axis=1)

array([10, 26, 42])