# What is NumPy?

A multidimensional array Python library.

In other words, NumPy enables you to create 1d arrays, 2d arrays, 3d arrays, and so on.

## How is NumPy different from Python Lists?

NumPy arrays use fixed types. For example, in a NumPy array, the number five only contains four bytes (i.e., 00000000 00000000 00000000 00000101). You can also cast this value as an `int16` or `int8`, which further reduces the memory required to store byte values.

Conversely, Python lists use a built-in int type, which consists of the following:

- The size
- Reference count
- Object type
- Object value

This means Python lists require additional memory to store an integer value. In this case, memory for the integer value itself (i.e., the number five) and additional memory for the reference count, object type, and object value.

Also, when iterating through a NumPy array, type checking each item isn't required since all the values are integer types. Conversely, because Python lists can store integers, booleans, strings, etc., type checking each item is required, which makes the entire process much slower.

And finally, NumPy is faster because it utilizes contiguous memory, while Python lists do not. This means the computer doesn't have to spend large amounts of time looking up values, as values reside next to each other in memory (i.e., effective cache utilization).

TL;DR: NumPy arrays are faster than Python lists.

## Python List

```
a = [1, 3, 5]
b = [1, 2, 3]
```

`a * b` returns an error

## NumPy Array

```
a = np.array([1, 3, 5])
b = np.array([1, 2, 3])
```

`a * b` will return `np.array([1, 6, 15])`

## Tools using NumPy

- Mathematics (MATLAB replacement)
- Plotting (e.g., matplotlib)
- Backend (e.g., pandas)
- Machine learning (e.g., tensor libraries)

In [6]:
import numpy as np

In [7]:
a = np.array([1, 2, 3])

In [8]:
a

array([1, 2, 3])

In [11]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [12]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a.ndim

1

In [15]:
b.ndim

2

In [16]:
a.shape

(3,)

In [17]:
b.shape

(2, 3)

In [18]:
a.dtype

dtype('int32')

In [19]:
a.itemsize

4

In [22]:
# bytes * number of values
# 4 * 3 = 12

a.nbytes

12

In [23]:
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [24]:
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [25]:
# get a specific element [row, column]
# return 13

c[1, 5]

13

In [27]:
# get a specific row
# return first row

c[0]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
# return first row

c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
# get a specific column
# return 3rd column (3 and 10 numbers)

c[:, 2]

array([ 3, 10])

In [41]:
# return 2, 4, 6 in first row

c[0, 1:6:2]

array([2, 4, 6])

In [44]:
# 3d array

d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [45]:
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [49]:
# get specific element
# return 4

d[0, 1, 1]

4

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [52]:
np.zeros((5, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
np.ones((4, 2, 2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [55]:
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [56]:
np.arange(1, 3)

array([1, 2])

In [58]:
# random decimal numbers
# returns numbers [0, 1)

np.random.rand(2, 2)

array([[0.92614662, 0.04030884],
       [0.10045737, 0.26581772]])

In [60]:
# return numbers [0, 1)

np.random.randint(5, size=(3, 3))

array([[3, 4, 4],
       [2, 4, 3],
       [2, 2, 0]])

In [61]:
# identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
e = np.ones((5, 5), dtype="int32")

In [69]:
e

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [71]:
e[2, 2] = 9

In [72]:
e

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 9, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [73]:
e[1, 1:4] = 0

In [74]:
e

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 9, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [75]:
e[3, 1:4] = 0

In [76]:
e

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 9, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [79]:
e[1:4, 1] = 0

In [80]:
e

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [81]:
e[1:4, 3] = 0

In [82]:
e

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [85]:
e = np.ones((5, 5), dtype="int32")

In [86]:
e

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [87]:
f = np.zeros((3, 3), dtype="int32")

In [88]:
f

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [89]:
f[1, 1] = 9

In [90]:
f

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [91]:
e[1:4, 1:4] = f

In [92]:
e

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [93]:
# be careful with copying arrays

a = np.array([1, 2, 3])

In [94]:
a

array([1, 2, 3])

In [95]:
b = a

In [96]:
b

array([1, 2, 3])

In [97]:
b[0] = 100

In [98]:
b

array([100,   2,   3])

In [99]:
# array a has 100 as well even though array b was modified
# this is because a and b are pointing to the same python object

a

array([100,   2,   3])

In [100]:
# to fix this, use copy()

a = np.array([1, 2, 3])
b = a.copy()

b[0] = 100

In [102]:
a

array([1, 2, 3])

In [103]:
b

array([100,   2,   3])

In [104]:
# mathematics

a = np.array([ 1, 2, 3])

In [105]:
a

array([1, 2, 3])

In [106]:
a += 2

In [107]:
a

array([3, 4, 5])

In [110]:
a -= 2

In [111]:
a

array([1, 2, 3])

In [112]:
a * 2

array([2, 4, 6])

In [113]:
a / 2

array([0.5, 1. , 1.5])

In [118]:
a ** 10

array([    1,  1024, 59049], dtype=int32)

In [119]:
# statistics

a = np.array([[1, 2, 3], [4, 5, 6]])

In [120]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
a.min()

1

In [123]:
a.max()

6

In [128]:
np.sum(a)

21

In [129]:
np.mean(a)

3.5

In [132]:
# axis = 1 for rows; axis = 0 for columns

np.sum(a, axis=1)

array([ 6, 15])

In [133]:
np.sum(a, axis=0)

array([5, 7, 9])